export const USERNAME_CHANGED = 'username_changed'
export const EMAIL_CHANGED = 'email_changed'
export const PASSWORD_CHANGED = 'password_changed'
export const REPASSWORD_CHANGED = 'repassword_changed'
export const LOGIN_USER_SUCCESS = 'login_user_success'
export const LOGIN_USER_FAIL = 'login_user_fail'
export const LOGIN_USER = 'login_user'

export const SIGNUP_USER = 'SIGNUP_USER'
export const SIGNUP_USER_FAIL = 'SIGNUP_USER_FAIL'
export const SIGNUP_USER_SUCCESS = 'SIGNUP_USER_SUCCESS'

export const GET_TRANSACTIONS_REQUEST = 'GET_TRANSACTIONS_REQUEST'
export const GET_TRANSACTIONS_FAILURE = 'GET_TRANSACTIONS_FAILURE'
export const GET_TRANSACTIONS_SUCCESS = 'GET_TRANSACTIONS_SUCCESS'
export const SORT_TRANSACTIONS = 'SORT_TRANSACTIONS'

export const GET_SUGGESTIONS = 'GET_SUGGESTIONS'
export const GET_SUGGESTIONS_FAILURE = 'GET_SUGGESTIONS_FAILURE'
export const GET_SUGGESTIONS_SUCCESS = 'GET_SUGGESTIONS_SUCCESS'

export const USERNAME_TRANSACTION_CHANGED = 'USERNAME_TRANSACTION_CHANGED'
export const AMOUNT_TRANSACTION_CHANGED = 'AMOUNT_TRANSACTION_CHANGED'
